# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_palavra_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavra',
            name='likes',
        ),
        migrations.AddField(
            model_name='palavra',
            name='art_chosen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='palavra',
            name='art_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='palavra',
            name='art_wrong',
            field=models.IntegerField(default=0),
        ),
    ]
