# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20180324_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='palavra',
            name='categ',
            field=models.CharField(default='ricardo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='palavra',
            name='art',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='palavra',
            name='art_right',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='palavra',
            name='art_wrong',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
