# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20180325_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavra',
            name='categ',
            field=models.CharField(blank=True, default='missing', max_length=100),
        ),
    ]
