# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-01 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180325_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavra',
            name='mean',
            field=models.CharField(max_length=200),
        ),
    ]
