# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-01 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20180401_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavra',
            name='word',
            field=models.CharField(max_length=200),
        ),
    ]
